---

- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install Docker
  pacman:
    name: 
      - docker
      - docker-compose
    state: present

- name: Add the user appending the group docker to the user's groups
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Make sure a service is running
  systemd:
    state: started
    name: docker